apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-service
  template:
    metadata:
      labels:
        app: go-service
    spec:
      containers:
        - name: go-service
          image: go-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_URL
              value: " my-release-redis-master.metrics.svc.cluster.local"
            - name: REDIS_PASSWORD
              value: "oV6vB7zuLG"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"